type: rpm-ostree
repos:
- https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
install:
  - gnome-shell-extension-tailscale-gnome-qs
  - nautilus-open-any-terminal
  - tuned
  - tuned-ppd
  - tuned-profiles-atomic
  - tuned-utils
  - tuned-utils-systemtap