name: bingo-os
description: Bingo's OS

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - type: akmods
    install:
      - openrazer
      - openrgb
      - xpadneo
      - xone
      - wl
      - v4l2loopback

  - type: bling
    install:
      - ublue-update
      - dconf-update-service
      - 1password

  - from-file: recipe-rpm-ostree.yml
  - from-file: recipe-default-flatpaks.yml

  - type: script
    scripts:
      - signing.sh
      - enable-services.sh
      - desktop-customizations.sh
