type: rpm-ostree
repos:
# Additional repos are defined in `config/files/etc/yum.repos.d`.
install:
  # System
  - bash-color-prompt
  - dbus-x11
  - distrobox
  - glow
  - gum
  - htop
  - iotop
  - kcron
  - lm_sensors
  - mosh
  - neofetch
  - p7zip
  - p7zip-plugins
  - playerctl
  - powertop
  - pulseaudio-utils
  - python3-pip
  - samba
  - samba-dcerpc
  - samba-ldb-ldap-modules
  - samba-winbind-clients
  - samba-winbind-modules
  - seahorse
  - solaar
  - steam-devices
  - tailscale
  - tmux
  - wireguard-tools
  - wl-clipboard
  - yaru-theme
  # Video
  - compat-ffmpeg4
  - ffmpeg
  - ffmpeg-libs
  - ffmpegthumbs
  - gstreamer1-plugin-libav 
  - gstreamer1-plugins-bad-free-extras 
  - gstreamer1-plugins-bad-freeworld 
  - gstreamer1-plugins-ugly 
  - gstreamer1-vaapi
  - igt-gpu-tools
  - intel-media-driver
  - libavcodec-freeworld
  - libva-utils
  # Gnome
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-gsconnect
  - nautilus-gsconnect
  # Development, containers, and virtualization
  - code
  - containerd.io
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - guestfs-tools
  - libvirt
  - libvirt-client
  - libvirt-daemon-config-network
  - libvirt-daemon-kvm
  - python3-libguestfs
  - qemu
  - qemu-char-spice
  - qemu-device-display-virtio-gpu
  - qemu-device-display-virtio-vga
  - qemu-device-usb-redirect
  - qemu-img
  - qemu-kvm
  - qemu-system-x86-core
  - qemu-user-binfmt
  - qemu-user-static
  - virt-install
  - virt-manager
  - virt-top
  - virt-viewer
remove:
  - firefox
  - firefox-langpacks
  - gnome-software
  - gnome-software-rpm-ostree
  - gnome-tour
  - power-profiles-daemon