name: bingo-os
description: Bingo's OS

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

modules:
  - type: akmods
    install:
      - openrazer
      - openrgb
      - xpadneo
      - xone
      - wl
      - v4l2loopback

  - type: bling
    install:
      - ublue-update
      - dconf-update-service
      - 1password

  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - from-file: recipe-rpm-ostree.yml
  - from-file: recipe-rpm-ostree-ublue-staging.yml
  - from-file: recipe-default-flatpaks.yml
  - from-file: recipe-fonts.yml

  - type: systemd
    system:
      enabled:
        - tuned.service
        - tailscaled.service
        - dconf-update.service
        - ublue-update.timer
        - docker.socket
    user:
      enabled:
        - podman.socket
  
  - type: gschema-overrides
    include:
      - zz1-bingo-os.gschema.override

  - type: script
    scripts:
      - desktop-customizations.sh

  - type: signing
