# image will be published to ghcr.io/<user>/<name>
name: bingo-os
# description will be included in the image's metadata
description: Bingo's OS

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README
      - etc: /etc 

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh

  - type: bling
    install:
      - ublue-update
      - dconf-update-service
      - 1password

  - type: akmods
    install:
      - openrazer
      - openrgb
      - xpadneo
      - xone
      - wl
      - v4l2loopback

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # System
      - bash-color-prompt
      - dbus-x11
      - distrobox
      - glow
      - gum
      - htop
      - iotop
      - kcron
      - lm_sensors
      - mosh
      - neofetch
      - p7zip
      - p7zip-plugins
      - playerctl
      - powertop
      - pulseaudio-utils
      - python3-pip
      - samba
      - samba-dcerpc
      - samba-ldb-ldap-modules
      - samba-winbind-clients
      - samba-winbind-modules
      - seahorse
      - solaar
      - steam-devices
      - tailscale
      - tmux
      - tuned
      - tuned-ppd
      - tuned-profiles-atomic
      - tuned-utils
      - tuned-utils-systemtap
      - wireguard-tools
      - wl-clipboard
      - yaru-theme
      # Video
      - compat-ffmpeg4
      - ffmpeg
      - ffmpeg-libs
      - ffmpegthumbs
      - gstreamer1-plugin-libav 
      - gstreamer1-plugins-bad-free-extras 
      - gstreamer1-plugins-bad-freeworld 
      - gstreamer1-plugins-ugly 
      - gstreamer1-vaapi
      - igt-gpu-tools
      - intel-media-driver
      - libavcodec-freeworld
      - libva-utils
      # Gnome
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-logo-menu
      - gnome-shell-extension-tailscale-gnome-qs
      - nautilus-gsconnect
      - nautilus-open-any-terminal
      # Fonts
      - adobe-source-code-pro-fonts
      - cascadia-code-fonts
      - google-droid-sans-mono-fonts
      - google-go-mono-fonts
      - ibm-plex-mono-fonts
      - jetbrains-mono-fonts-all
      - mozilla-fira-mono-fonts
      - nerd-fonts
      - powerline-fonts
      - ubuntu-family-fonts
      # Development, containers, and virtualization
      - code
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - guestfs-tools
      - libvirt
      - libvirt-client
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - python3-libguestfs
      - qemu
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-kvm
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - virt-install
      - virt-manager
      - virt-top
      - virt-viewer
    remove:
      - firefox
      - firefox-langpacks
      # - gnome-extensions-app
      - gnome-software
      - gnome-software-rpm-ostree
      - gnome-tour
      - tlp
      - tlp-rdw
      - power-profiles-daemon

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
      # Utilities
      - com.github.tchx84.Flatseal
      - com.github.unrud.VideoDownloader
      - com.mattjakeman.ExtensionManager
      - io.github.fabrialberio.pinapp
      - it.mijorus.gearlever
      - org.gustavoperedo.FontDownloader
      - org.mozilla.firefox
      remove:
      # - org.gnome.eog
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
      # Utilities
      - com.github.zocker_160.SyncThingy
      - com.github.marhkb.Pods
      # Communication/Web
      - com.discordapp.Discord
      - org.gnome.Epiphany # For PWAs
      - com.microsoft.Edge # For MS Teams / Office.
      - us.zoom.Zoom
      # Entertainment
      - com.moonlight_stream.Moonlight
      - com.valvesoftware.Steam
      - com.spotify.Client
      - sh.cider.Cider
