type: fonts
fonts:
  nerd-fonts:
    - NerdFontsSymbolsOnly
  google-fonts:
    - Fira Code
    - Fira Mono
    - Fira Sans
    - Inconsolata
    - Inter
    - JetBrains Mono
    - Lato
    - Merriweather
    - Noto Sans
    - Noto Serif
    - Open Sans
    - Roboto
    - Roboto Mono
    - Roboto Serif
    - Roboto Slab
    - Source Code Pro
    - Ubuntu
    - Ubuntu Mono