type: default-flatpaks
notify: true
system:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub
  install:
  # OS Apps
  - org.fedoraproject.MediaWriter
  - org.gnome.baobab
  - org.gnome.Calculator
  - org.gnome.Characters
  - org.gnome.Cheese
  - org.gnome.clocks
  - org.gnome.Connections
  - org.gnome.Evince
  - org.gnome.font-viewer
  - org.gnome.Logs
  - org.gnome.Loupe
  - org.gnome.NautilusPreviewer
  - org.gnome.TextEditor
  # Utilities
  - com.github.tchx84.Flatseal
  - com.github.unrud.VideoDownloader
  - com.mattjakeman.ExtensionManager
  - io.github.fabrialberio.pinapp
  - io.missioncenter.MissionCenter
  - it.mijorus.gearlever
  - org.gustavoperedo.FontDownloader
  - org.localsend.localsend_app
  - org.mozilla.firefox
user:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub
  install:
  # Utilities
  - com.github.zocker_160.SyncThingy
  - com.github.marhkb.Pods
  # Communication/Web
  - com.discordapp.Discord
  - org.gnome.Epiphany # For PWAs
  - com.microsoft.Edge # For MS Teams / Office.
  - us.zoom.Zoom
  # Entertainment
  - com.moonlight_stream.Moonlight
  - com.valvesoftware.Steam
  - com.spotify.Client
  - sh.cider.Cider
