name: bingo-os
description: Bingo's OS

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr
      - etc: /etc

  - type: akmods
    install:
      - openrazer
      - openrgb
      - xpadneo
      - xone
      - wl
      - v4l2loopback

  - type: bling
    install:
      - ublue-update
      - dconf-update-service
      - 1password

  - from-file: recipe-rpm-ostree.yml
  - from-file: recipe-default-flatpaks.yml

  - type: fonts
    fonts:
      nerd-fonts:
        - DroidSansMono
        - FiraCode
        - FiraMono
        - GeistMono
        - Go-Mono
        - Hack
        - Inconsolata
        - JetBrainsMono
        - NerdFontsSymbolsOnly
        - ProFont
        - RobotoMono
        - SourceCodePro
        - Terminus
        - Ubuntu
        - UbuntuMono
      google-fonts:
        - Fira Sans
        - Inter
        - Lato
        - Merriweather
        - Noto Sans
        - Noto Serif
        - Open Sans
        - Roboto
        - Roboto Slab

  - type: systemd
    system:
      enabled:
        - tuned.service
        - rpm-ostree-countme.service
        - tailscaled.service
        - dconf-update.service
        - ublue-update.timer
        - docker.socket
  
  - type: gschema-overrides
    include:
      - zz1-bingo-os.gschema.override

  - type: script
    scripts:
      - desktop-customizations.sh

  - type: signing